'use strict';

/**
 * @namespace modules
 */
module.exports = {
	modules: exports,
	capitalise: require('./capitalise'),
	charLimit: require('./charLimit'),
	commandError: require('./commandError'),
	dateTimeGroup: require('./dateTimeGroup'),
	debugError: require('./debugError'),
	deleteMsg: require('./deleteMsg'),
	difference: require('./difference'),
	directCommandError: require('./directCommandError'),
	embedScaffold: require('./embedScaffold'),
	emojiReact: require('./emojiReact'),
	enumerateResources: require('./enumerateResources'),
	equals: require('./equals'),
	errorReact: require('./errorReact'),
	formatAge: require('./formatAge'),
	formatList: require('./formatList'),
	getRoleError: require('./getRoleError'),
	isURL: require('./isURL'),
	jsCodeBlock: require('./jsCodeBlock'),
	merge: require('./merge'),
	prefixCommand: require('./prefixCommand'),
	processResources: require('./processResources'),
	promptEmbed: require('./promptEmbed'),
	purgeChannel: require('./purgeChannel'),
	remove: require('./remove'),
	rolesOutput: require('./rolesOutput'),
	sendDirect: require('./sendDirect'),
	sendMsg: require('./sendMsg'),
	sortByRoles: require('./sortByRoles'),
	stripID: require('./stripID'),
	successReact: require('./successReact'),
	titleCase: require('./titleCase'),
	updatedPermissions: require('./updatedPermissions'),
};