const mongoose = require('mongoose');

const guildSchema = mongoose.Schema({
	_id: mongoose.Schema.Types.ObjectId,
	guildID: String,
	guildName: String,
	prefix: String,
	dateOutput: String,
	prontoLogo: String,
	debugID: String,
	logID: String,
	attendanceID: String,
	recruitingID: String,
	newMembersID: String,
	archivedID: String,
	exampleTextID: String,
	exampleVoiceID: String,
	everyoneID: String,
	visitorID: String,
	administratorID: String,
	formations: Array,
	nonCadet: Array,
	tacPlus: Array,
	sgtPlus: Array,
	cqmsPlus: Array,
	adjPlus: Array,
	emojiSuccess: String,
	emojiError: String,
	colourDefault: Number,
	colourPronto: Number,
	colourLeave: Number,
	colourSuccess: Number,
	colourWarn: Number,
	colourError: Number,
});

module.exports = mongoose.model('Guild', guildSchema, 'guilds');